runtime: nodejs18
service: receipt-extractor

env_variables:
  NODE_ENV: production
  GEMINI_API_KEY: "AIzaSyAQrLDliNV3hdbYWYBxaESnv-HRinRFDUY"

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6

resources:
  cpu: 2
  memory_gb: 2

handlers:
- url: /.*
  script: auto
  secure: always
