import { useState } from 'react';
import { X } from 'lucide-react';
import { Button } from './ui/button';
import { useToast } from '@/hooks/use-toast';

interface SendCSVModalProps {
  isOpen: boolean;
  onClose: () => void;
  extractedRows: any[];
}

const blockedDomains = [
  'gmail.com', 'yahoo.com', 'outlook.com', 'hotmail.com', 'icloud.com',
  'aol.com', 'proton.me', 'zoho.com', 'gmx.com', 'yandex.com', 'live.com', 'msn.com'
];

function isBusinessEmail(email: string): boolean {
  const match = String(email || '').toLowerCase().match(/@([^@]+)$/);
  return match ? !blockedDomains.includes(match[1]) : false;
}

export const SendCSVModal = ({ isOpen, onClose, extractedRows }: SendCSVModalProps) => {
  const [email, setEmail] = useState('');
  const [error, setError] = useState('');
  const [isSending, setIsSending] = useState(false);
  const { toast } = useToast();

  if (!isOpen) return null;

  const handleClose = () => {
    setEmail('');
    setError('');
    setIsSending(false);
    onClose();
  };

  const handleSend = async () => {
    const trimmedEmail = email.trim();
    
    if (!trimmedEmail) {
      setError('Email is required');
      return;
    }

    if (!isBusinessEmail(trimmedEmail)) {
      setError('Use a business email.');
      return;
    }

    setError('');
    setIsSending(true);

    try {
      const API_URL = import.meta.env.DEV 
        ? 'http://localhost:3001/api/send-csv'
        : '/api/send-csv';

      console.log('[SendCSVModal] Sending CSV to:', API_URL);
      console.log('[SendCSVModal] Email:', trimmedEmail);
      console.log('[SendCSVModal] Rows count:', extractedRows.length);

      const response = await fetch(API_URL, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          email: trimmedEmail,
          filename: 'mesh-receipts.csv',
          rows: extractedRows
        })
      });

      console.log('[SendCSVModal] Response status:', response.status);
      console.log('[SendCSVModal] Response ok:', response.ok);

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({ error: 'Unknown error' }));
        console.error('[SendCSVModal] Error response:', errorData);
        throw new Error(errorData.error || `Server error: ${response.status}`);
      }

      const result = await response.json();
      console.log('[SendCSVModal] Success:', result);

      toast({
        title: 'CSV sent',
        description: 'Check your inbox.',
      });

      setTimeout(() => {
        handleClose();
      }, 900);
    } catch (e: any) {
      console.error('[SendCSVModal] Error:', e);
      setIsSending(false);
      const errorMessage = e?.message || 'Could not send, try again.';
      setError(errorMessage);
    }
  };

  return (
    <div 
      className="modal-overlay"
      onClick={(e) => {
        if (e.target === e.currentTarget) {
          handleClose();
        }
      }}
    >
      <div className="modal-card">
        <div className="flex items-center justify-between mb-4">
          <h3 className="modal-title">Send your CSV</h3>
          <button
            onClick={handleClose}
            className="text-gray-400 hover:text-gray-600 transition-colors"
            aria-label="Close modal"
          >
            <X className="h-5 w-5" />
          </button>
        </div>
        
        <p className="modal-sub">
          Enter your work email and we will send the CSV generated by Mesh AI.
        </p>

        <div className="field">
          <label htmlFor="csv-email" className="field-label">
            Work email
          </label>
          <input
            id="csv-email"
            type="email"
            placeholder="name@company.com"
            value={email}
            onChange={(e) => {
              setEmail(e.target.value);
              setError('');
            }}
            onKeyDown={(e) => {
              if (e.key === 'Enter' && !isSending) {
                handleSend();
              }
            }}
            className={`field-input ${error ? 'border-red-500' : ''}`}
            required
            disabled={isSending}
          />
          {error && (
            <small className="error">{error}</small>
          )}
        </div>

        <div className="modal-actions">
          <button
            id="csv-cancel"
            className="btn-neutral"
            onClick={handleClose}
            disabled={isSending}
          >
            Cancel
          </button>
          <button
            id="csv-send"
            className="btn-primary"
            onClick={handleSend}
            disabled={isSending}
          >
            {isSending ? 'Sending...' : 'Send'}
          </button>
        </div>

        <p className="tiny-legal">
          We use your email only to send the CSV. You can unsubscribe at any time. See our{' '}
          <a href="/privacy" target="_blank" rel="noopener" className="underline">
            Privacy Policy
          </a>.
        </p>
      </div>
    </div>
  );
};

